### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by partoneoftwo** [croxis/planetrise#2]
Hi there

I would like to see a screenshot of this plugin. It sounds cool!

**Comment by KristjanESPERANTO** [comment]
@croxis: A screenshot would be really nice for [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by croxis** [comment]
![image](https://github.com/croxis/planetrise/assets/121591/3d75c6ad-6573-49bb-a66c-d6e6f9e42e93)
